---
spec/spec_helper.rb:
  mock_with: ':rspec'
Gemfile:
  optional:
    ':development':
      - gem: pry-byebug
.rubocop.yml:
  profiles:
    strict:
      configs:
        AllCops:
          TargetRubyVersion: '2.4'
